INSERT INTO bienes.sub_grupos ("codigo", "descripcion") VALUES
  ('2-01','MAQUINAS, MUEBLES Y DEMAS EQUIPOS DE OFICINA'),
  ('2-02','MOBILIARIO Y ENSERES DE  ALOJAMIENTO'),
  ('2-03','MAQUINARIAS Y DEMAS EQUIPOS DE CONTRUCCION, CAMPO, INDUSTRIA Y TALLER.'),
  ('2-04','EQUIPOS DE TRANSPORTE.'),
  ('2-05','EQUIPOS DE TELECOMUNICACIONES.'),
  ('2-06','EQUIPOS MEDICO-QUIRURGICOS, DENTALES Y VETERINARIOS.'),
  ('2-07','EQUIPOS CIENTIFICOS Y DE ENSEÑANZA.'),
  ('2-08','COLECCIONES CULTURALES; ARTISTICAS E HISTORICAS.'),
  ('2-11','SEMOVIENTES.'),
  ('2-12','OTROS ELEMENTOS.');